#
# List of applications to deploy with ArgoCD
#
backendRepo: "https://github.com/dsilevi/ds-backend-infrastructure"
appRepo: "https://istio-release.storage.googleapis.com/charts"
appBaseVersion: "1.22.1"
appBaseChart: "base"
appBaseName: "istio-base"
appBasePath: "environment/default/istio-system/base"
appNamespace: "istio-system"
appValueFiles:
  - values.yaml
project: "default"
server: "https://kubernetes.default.svc"
